spring.application.name=AutoMessager
spring.datasource.url=jdbc:postgresql://localhost:5432/sedrak
spring.datasource.username=postgres
spring.datasource.password=POSTGRES
spring.jpa.hibernate.ddl-auto=update
